### PR TITLE
#45 Bump com.google.errorprone:error_prone_core to 2.49.0

### PR DESCRIPTION
**Pull request by fabian-barney**
## Implementation Summary
- Scope: refresh the `error_prone_core` 2.49.0 bump from PR #45 onto current `main`.
- Key changes: update `pom.xml` from `2.48.0` to `2.49.0` and validate the full PR workflow commands on current `main`.
- Non-goals: no source-code changes, no behavior changes, and no dependency additions beyond the requested version bump.

## Validation
- Tests executed: `./mvnw -B -ntp -Pnullaway test`; `./mvnw -B -ntp -P!quality-gates-all,quality-gate-crap verify`; `./mvnw -B -ntp -P!quality-gates-all,quality-gate-cognitive verify`
- Manual checks: confirmed the repository does not use the Error Prone APIs removed in 2.49.0.
- Residual risks: the original dependabot PR #45 failed on its older branch state; this replacement PR is validated on current `main`.

Supersedes #45.

### CODE REVIEW

**Comment by fabian-barney** [comment]
Follow-up after the failing pipeline repro:

The failing `-Pnullaway` job was not caused by project source code. A clean compile with `error_prone_core=2.49.0` failed while initializing NullAway:

- `java.lang.NoClassDefFoundError: com/google/errorprone/predicates/type/DescendantOf`

`NullAway 0.13.1` still referenced an Error Prone API removed in 2.49.0. I aligned `nullaway.version` to `0.13.2`, which is the first NullAway release that explicitly updates to Error Prone 2.49.0.

Clean local validation after the fix:
- `./mvnw -B -ntp -Pnullaway clean test`
- `./mvnw -B -ntp -P!quality-gates-all,quality-gate-crap clean verify`
- `./mvnw -B -ntp -P!quality-gates-all,quality-gate-cognitive clean verify`
